Specify package_data in setup.py (minecraft.yaml must be included).
pymclevel requires minecraft.yaml to be shipped, otherwise

IOError: [Errno 2] No such file or directory: 'pymclevel/minecraft.yaml'